
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/schedulemedevelopment

test:
  <<: *default
  database: db/schedulemetest

production:
  <<: *default
  database: db/schedulemeproduction
